#!/bin/sh

# Parse date argument
date=20170228

if [[ -n $1 ]]
then
    date=$1
fi

date_length=${#date}
if [[ $date_length != 8 ]]
then
    echo 'Invalid date. Example: 20170228'
    exit
fi

echo 'Aggregating for date: '$date

# Results will be put here
location=/cms/users/$USER/dbs_datasets
hdir=hdfs://$location

# Remove previous data first
hadoop fs -rm -r $location

PYTHONPATH=$(pwd)/../../python ../../../bin/run_spark /reports/aggregate_dbs.py --fout=$hdir --yarn --verbose

hadoop fs -test -e $hdir
exists=$?

# Download results and recreate csv files only if results exist in hdfs
if [[ $exists -eq 0 ]]
then
    # Delete previously downloaded directory and download new one
    basename $hdir | xargs rm -rf
    hadoop fs -get $hdir .

    # extract header
    head -1 dbs_datasets/part-00000 > dbs_df.csv

    # concatenate all parts except header
    header=`cat dbs_df.csv`
    cat dbs_datasets/part* | grep -v $header >> dbs_df.csv
fi
