#!/bin/sh

# Treat first argument as date. 
# Date will be validated in actual scripts below.
date=$1

# Treat second argument as hdfs result location. 
location=$2

# Get current script's absolute path
scriptpath="$( cd "$(dirname "$0")" ; pwd -P )"

# Aggregate dbs data
$scriptpath/aggregate_dbs $location &

# Aggregate PhEDEx
$scriptpath/aggregate_phedex $date $location &

wait
