#!/bin/sh

location=/cms/users/$USER/dbs_datasets

if [[ -n $1 ]]
then
    location=$1
fi

echo 'Results path: '$location

# Results will be put here
hdir=hdfs://$location

# Get current script's absolute path
scriptpath="$( cd "$(dirname "$0")" ; pwd -P )"

# Remove previous data first
hadoop fs -rm -r $location

PYTHONPATH=$scriptpath/../../python $scriptpath/../../../bin/run_spark /reports/aggregate_dbs.py --fout=$hdir --yarn --verbose

hadoop fs -test -e $hdir
exists=$?

# Download results and recreate csv files only if results exist in hdfs
if [[ $exists -eq 0 ]]
then
    # Delete previously downloaded directory and download new one
    rm -rf "$scriptpath/$(basename $hdir)"
    hadoop fs -get $hdir $scriptpath

    # extract header
    head -1 $scriptpath/dbs_datasets/part-00000 > $scriptpath/dbs_df.csv

    # concatenate all parts except header
    header=`cat $scriptpath/dbs_df.csv`
    cat $scriptpath/dbs_datasets/part* | grep -v $header >> $scriptpath/dbs_df.csv
fi
