#!/bin/sh

# Parse date argument
date=20170228

if [[ -n $1 ]]
then
    date=$1
fi

date_length=${#date}
if [[ $date_length != 8 ]]
then
    echo 'Invalid date. Example: 20170228'
    exit
fi

echo 'Aggregating for date: '$date

# Get current script's absolute path
scriptpath="$( cd "$(dirname "$0")" ; pwd -P )"

# Results will be put here
location=/cms/users/$USER/leftovers
hdir=hdfs://$location

# Remove previous data first
hadoop fs -rm -r $location

PYTHONPATH=$scriptpath/../../python $scriptpath/../../../bin/run_spark /reports/aggregate_leftovers.py --fout=$hdir --yarn --verbose --date=$date

hadoop fs -test -e $hdir
exists=$?

# Download results and recreate csv files only if results exist in hdfs
if [[ $exists -eq 0 ]]
then
    # Delete previously downloaded directory and download new one
    #basename $hdir | xargs rm -rf
    rm -rf $scriptpath/$(basename $hdir)
    hadoop fs -get $hdir $scriptpath

    # Extract all leftovers header
    head -1 $scriptpath/leftovers/all/part-00000 > $scriptpath/leftovers_all_df.csv

    # Concatenate all parts except header
    header=`cat $scriptpath/leftovers_all_df.csv`
    cat $scriptpath/leftovers/all/part* | grep -v $header >> $scriptpath/leftovers_all_df.csv

    # Copy to cernbox directory
    cp $scriptpath/leftovers_all_df.csv /eos/user/a/$USER/leftovers/leftovers_all_df.csv
    
    (cd /eos/user/a/$USER/leftovers/; echo 'Dataframe availible here:' $(pwd)/'leftovers_all_df.csv')

    # Extract orphan leftovers header
    head -1 $scriptpath/leftovers/orphans/part-00000 > $scriptpath/leftovers_orphans_df.csv

    # Concatenate all parts except header
    header=`cat $scriptpath/leftovers_orphans_df.csv`
    cat $scriptpath/leftovers/orphans/part* | grep -v $header >> $scriptpath/leftovers_orphans_df.csv

    # Copy to cernbox directory
    cp $scriptpath/leftovers_orphans_df.csv /eos/user/a/$USER/leftovers/leftovers_orphans_df.csv
    
    (cd /eos/user/a/$USER/leftovers/; echo 'Dataframe availible here:' $(pwd)/'leftovers_orphans_df.csv')
fi
