#!/bin/sh

# Parse date argument
date=20170228

if [[ -n $1 ]]
then
    date=$1
fi

date_length=${#date}
if [[ $date_length != 8 ]]
then
    echo 'Invalid date. Example: 20170228'
    exit
fi

echo 'Aggregating for date: '$date

# Get current script's absolute path
scriptpath="$( cd "$(dirname "$0")" ; pwd -P )"

# Results will be put here
location=/cms/users/$USER/leftovers
hdir=hdfs://$location

# Remove previous data first
hadoop fs -rm -r $location

PYTHONPATH=$scriptpath/../../python $scriptpath/../../../bin/run_spark /reports/aggregate_leftovers.py --fout=$hdir --yarn --verbose --date=$date

hadoop fs -test -e $hdir
exists=$?

# Download results and recreate csv files only if results exist in hdfs
if [[ $exists -eq 0 ]]
then
    # Delete previously downloaded directory and download new one
    basename $hdir | xargs rm -rf
    hadoop fs -get $hdir .

    # Extract PhEDEx header
    head -1 leftovers/part-00000 > leftovers_df.csv

    # Concatenate all PhEDEx parts except header
    header=`cat leftovers_df.csv`
    cat leftovers/part* | grep -v $header >> leftovers_df.csv

    cp leftovers_df.csv ~/public/leftovers_df.csv
fi
