# cmsmon-gen-crsg-plots
FROM registry.cern.ch/cmsmonitoring/cmsmon-spark:test
LABEL maintainer="Carlos Borrajo Gomez carlos.borrajo.gomez@cern.ch"

ENV WDIR=/opt/spark-apps/gen-crsg-plots
WORKDIR $WDIR

COPY src/ $WDIR/

