# cmsmon-crab-unique-users
FROM registry.cern.ch/cmsmonitoring/cmsmon-spark:test
MAINTAINER Carlos Borrajo Gomez carlos.borrajo.gomez@cern.ch 

ENV WDIR=/opt/spark-apps/crab-unique-users
WORKDIR $WDIR

COPY src/ $WDIR

