#!/bin/sh

# Parse date argument
date=''

if [[ -n $1 ]]
then
    date=$1
fi

date_length=${#date}
if [[ $date_length != 8 ]]
then
    echo 'Invalid date. Correct format: YYYYMMDD. Example: 20170228'
    exit
fi

echo 'Aggregating for date: '$date

location=/cms/users/$USER/leftovers

if [[ -n $2 ]]
then
    location=$2
fi

echo 'Results path: '$location

inst='all'
if [[ -n $3 ]]
then
    inst=$3
fi

echo 'DBS instances: '$inst

# Results will be put here
hdir=hdfs://$location

# Get current script's absolute path
scriptpath="$( cd "$(dirname "$0")" ; pwd -P )"

# Remove previous data first
hadoop fs -rm -r $location

PYTHONPATH=$scriptpath/../../python $scriptpath/../../../bin/run_spark /reports/aggregate_leftovers.py --fout=$hdir --yarn --verbose --date=$date --inst=$inst

hadoop fs -test -e $hdir
exists=$?

# Download results and recreate csv files only if results exist in hdfs
if [[ $exists -eq 0 ]]
then
    result_dir="$(basename $hdir)"

    # Delete previously downloaded directory and download new one
    rm -rf "$scriptpath/$result_dir"
    hadoop fs -get $hdir $scriptpath

    # Extract all leftovers header
    head -1 $scriptpath/$result_dir/all/part-00000 > $scriptpath/leftovers_all_df.csv

    # Concatenate all parts except header
    header=`cat $scriptpath/leftovers_all_df.csv`
    cat $scriptpath/$result_dir/all/part* | grep -v $header >> $scriptpath/leftovers_all_df.csv

    # Extract orphan leftovers header
    head -1 $scriptpath/$result_dir/orphans/part-00000 > $scriptpath/leftovers_orphans_df.csv

    # Concatenate all parts except header
    header=`cat $scriptpath/leftovers_orphans_df.csv`
    cat $scriptpath/$result_dir/orphans/part* | grep -v $header >> $scriptpath/leftovers_orphans_df.csv

    # Uncomment following lines if you want to copy results to cernbox directory
    #cp $scriptpath/leftovers_all_df.csv /eos/user/a/$USER/leftovers/leftovers_all_df.csv
    #cp $scriptpath/leftovers_orphans_df.csv /eos/user/a/$USER/leftovers/leftovers_orphans_df.csv
    #(cd /eos/user/a/$USER/leftovers/; echo 'Dataframe availible here:' $(pwd)/'leftovers_all_df.csv')
    #(cd /eos/user/a/$USER/leftovers/; echo 'Dataframe availible here:' $(pwd)/'leftovers_orphans_df.csv')
fi
